version: '0.3'

services:
  app:
    image: ghcr.io/arguswarp/food-observer-bot:latest
    container_name: fobs-maven
    mem_limit: 250m
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_URL=$DB_URL
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - BOT_TOKEN=$BOT_TOKEN
      - BOT_NAME=$BOT_NAME
      - EXCEL_PATH=$EXCEL_PATH
      - TZ=$TIME_ZONE
    ports:
      - 8080:8080
    networks:
      - fobs-net
    restart: unless-stopped
  db:
    image: postgres:$PG_VERSION
    container_name: fobs-db
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_PORT=$DB_PORT
      - POSTGRES_VERSION=$PG_VERSION
    ports:
      - $DB_PORT:5432
    networks:
      - fobs-net
    volumes:
      - fobs_data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
volumes:
  fobs_data:
networks:
  fobs-net:
