version: '0.1'

services:
  app:
    image: ghcr.io/arguswarp/food-observer-bot:latest
    container_name: fobs-maven
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - APP_PORT=$APP_PORT
      - DB_URL=$DB_URL
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - BOT_TOKEN=$BOT_TOKEN
      - BOT_NAME=$BOT_NAME
      - EXCEL_PATH=$EXCEL_PATH
    ports:
      - $APP_PORT:8082
    networks:
      - fobs-net
    restart: unless-stopped
  db:
    image: postgres:$PG_VERSION
    container_name: fobs-db
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_PORT=$DB_PORT
      - POSTGRES_VERSION=$PG_VERSION
    ports:
      - $DB_PORT:5432
    networks:
      - fobs-net
    volumes:
      - fobs_data:/var/lib/postgresql/data
volumes:
  fobs_data:
networks:
  fobs-net:
