scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.0.12:9090' ]

  - job_name: 'BotMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.12:8080']
        labels:
          application: 'My Spring Boot Application'