-- liquibase formatted sql
-- changeset argus:1
create table food_record
(
    id         bigint primary key generated by default as identity,
    food       varchar(100),
    created_at timestamp without time zone,
    is_bloody  boolean,
    is_pimple  boolean,
    username   varchar(100)
);

