name: Docker Image CI for GHCR

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_PORT: ${{ vars.APP_PORT }}

      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_NAME: ${{ secrets.BOT_NAME }}

      EXCEL_PATH: ${{ vars.EXCEL_PATH }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push the Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/food-observer-bot:latest